version: '3.3'

services:
  database:
    image: "mysql:5.7"
    container_name: "mysql1"
    ports:
      - "6604:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      DATABASE_HOST: database
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: test
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password

  service:
    build: .
    image: "node"
    container_name: "nodejs"
    ports:
      - "8080:8080"
    depends_on:
      - database
    links:
      - database
    environment:
      DATABASE_HOST: database
      MYSQL_PORT: 3306
      MYSQL_DATABASE: test
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
    restart: on-failure