version: '2'
services: 
  db:
    build: mysql-microservice
    ports:
      - "3307:3306"  
  app:
      build: nodejs-microservice
      command: node_modules/.bin/nodemon --exec npm start
      environment:
        ENVIRONMENT: development
      ports:
        - "3307:3306" 
      links:
        - db:db 
     